apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: finnfastlege
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /health/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /health/isReady
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  # prometheus:
  #   enabled: false
  #   path: /actuator/metrics
  vault:
    enabled: true
  env:
    - name: ENV
      value: production
    - name: HOST
      value: finnfastlege.intern.nav.no
    - name: NODE_ENV
      value: production
    - name: REDIS_HOST
      value: finnfastlege-redis
    - name: FINNFASTLEGE_URL
      value: http://finnfastlege
    - name: AUTH_REDIRECT_URI
      value: "https://finnfastlege.intern.nav.no/oauth2/callback"
    - name: FASTLEGEREST_AAD_APP_CLIENT_ID
      value: "eba0340e-61f5-458d-beef-3ef7520eac3a"
    - name: SYFOPERSON_AAD_APP_CLIENT_ID
      value: "65bd6a4c-e757-487f-9767-619a5307278f"
    - name: SYFOTILGANGSKONTROLL_AAD_APP_CLIENT_ID
      value: "dfaa2699-7390-4459-9cfc-2e8de64dfaf9"
    - name: MODIACONTEXTHOLDER_HOST
      value: "https://modiacontextholder.nais.adeo.no"
    - name: FASTLEGEREST_HOST
      value: "https://fastlegerest.intern.nav.no"
    - name: SYFOPERSON_HOST
      value: "https://syfoperson.intern.nav.no"
    - name: SYFOTILGANGKONTROLL_HOST
      value: "https://syfo-tilgangskontroll.intern.nav.no"
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
      replyURLs:
        - "https://finnfastlege.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  webproxy: true
  ingresses:
    - "https://finnfastlege.intern.nav.no"
