apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: finnfastlege
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /health/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /health/isReady
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  # prometheus:
  #   enabled: false
  #   path: /actuator/metrics
  vault:
    enabled: true
  env:
    - name: ENV
      value: preprod
    - name: HOST
      value: finnfastlege.dev.intern.nav.no
    - name: NODE_ENV
      value: production
    - name: REDIS_HOST
      value: finnfastlege-redis
    - name: FINNFASTLEGE_URL
      value: http://finnfastlege
    - name: AUTH_REDIRECT_URI
      value: "https://finnfastlege.dev.intern.nav.no/oauth2/callback"
    - name: FASTLEGEREST_AAD_APP_CLIENT_ID
      value: "f5510c3d-2510-444d-91a2-5790c1ec39a4"
    - name: SYFOPERSON_AAD_APP_CLIENT_ID
      value: "10ce50ea-d922-48d7-888d-3f8b683d8aab"
    - name: SYFOTILGANGSKONTROLL_AAD_APP_CLIENT_ID
      value: "32e36aa5-1d12-452a-9b1e-9f3f557cbb4d"
    - name: MODIACONTEXTHOLDER_HOST
      value: "https://modiacontextholder-q0.dev.adeo.no"
    - name: FASTLEGEREST_HOST
      value: "https://fastlegerest.dev.intern.nav.no"
    - name: SYFOPERSON_HOST
      value: "https://syfoperson.dev.intern.nav.no"
    - name: SYFOTILGANGKONTROLL_HOST
      value: "https://syfo-tilgangskontroll.dev.intern.nav.no"
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - "https://finnfastlege.dev.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  webproxy: true
  ingresses:
    - "https://finnfastlege.dev.intern.nav.no"
